package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LmLocationsHasUmUser generated by hbm2java
 */
public class LmLocationsHasUmUser  implements java.io.Serializable {


     private LmLocationsHasUmUserId id;
     private LmLocations lmLocations;
     private UmUser umUser;
     private Boolean isActive;
     private Date createdAt;
     private Date updatedAt;
     private Integer createdBy;
     private Integer updatedBy;

    public LmLocationsHasUmUser() {
    }

	
    public LmLocationsHasUmUser(LmLocationsHasUmUserId id, LmLocations lmLocations, UmUser umUser) {
        this.id = id;
        this.lmLocations = lmLocations;
        this.umUser = umUser;
    }
    public LmLocationsHasUmUser(LmLocationsHasUmUserId id, LmLocations lmLocations, UmUser umUser, Boolean isActive, Date createdAt, Date updatedAt, Integer createdBy, Integer updatedBy) {
       this.id = id;
       this.lmLocations = lmLocations;
       this.umUser = umUser;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public LmLocationsHasUmUserId getId() {
        return this.id;
    }
    
    public void setId(LmLocationsHasUmUserId id) {
        this.id = id;
    }
    public LmLocations getLmLocations() {
        return this.lmLocations;
    }
    
    public void setLmLocations(LmLocations lmLocations) {
        this.lmLocations = lmLocations;
    }
    public UmUser getUmUser() {
        return this.umUser;
    }
    
    public void setUmUser(UmUser umUser) {
        this.umUser = umUser;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


