package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LmLocationHistory generated by hbm2java
 */
public class LmLocationHistory  implements java.io.Serializable {


     private Integer id;
     private LmLocations lmLocations;
     private String updateDescription;
     private Date createdAt;
     private Date updatedAt;
     private Integer createdBy;
     private Integer updatedBy;

    public LmLocationHistory() {
    }

	
    public LmLocationHistory(LmLocations lmLocations) {
        this.lmLocations = lmLocations;
    }
    public LmLocationHistory(LmLocations lmLocations, String updateDescription, Date createdAt, Date updatedAt, Integer createdBy, Integer updatedBy) {
       this.lmLocations = lmLocations;
       this.updateDescription = updateDescription;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LmLocations getLmLocations() {
        return this.lmLocations;
    }
    
    public void setLmLocations(LmLocations lmLocations) {
        this.lmLocations = lmLocations;
    }
    public String getUpdateDescription() {
        return this.updateDescription;
    }
    
    public void setUpdateDescription(String updateDescription) {
        this.updateDescription = updateDescription;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }




}


