package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LmLocations generated by hbm2java
 */
public class LmLocations  implements java.io.Serializable {


     private Integer id;
     private UmUser umUser;
     private String locationName;
     private String locationAddress;
     private String mobileNumber;
     private String landPhoneNumber;
     private Boolean isActive;
     private Date createdAt;
     private Date updatedAt;
     private Integer createdBy;
     private Integer updatedBy;
     private Set<LmLocationsHasUmUser> lmLocationsHasUmUsers = new HashSet<LmLocationsHasUmUser>(0);
     private Set<UmCustomer> umCustomers = new HashSet<UmCustomer>(0);
     private Set<TmTickets> tmTicketses = new HashSet<TmTickets>(0);
     private Set<LmLocationHistory> lmLocationHistories = new HashSet<LmLocationHistory>(0);

    public LmLocations() {
    }

	
    public LmLocations(UmUser umUser) {
        this.umUser = umUser;
    }
    public LmLocations(UmUser umUser, String locationName, String locationAddress, String mobileNumber, String landPhoneNumber, Boolean isActive, Date createdAt, Date updatedAt, Integer createdBy, Integer updatedBy, Set<LmLocationsHasUmUser> lmLocationsHasUmUsers, Set<UmCustomer> umCustomers, Set<TmTickets> tmTicketses, Set<LmLocationHistory> lmLocationHistories) {
       this.umUser = umUser;
       this.locationName = locationName;
       this.locationAddress = locationAddress;
       this.mobileNumber = mobileNumber;
       this.landPhoneNumber = landPhoneNumber;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
       this.umCustomers = umCustomers;
       this.tmTicketses = tmTicketses;
       this.lmLocationHistories = lmLocationHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UmUser getUmUser() {
        return this.umUser;
    }
    
    public void setUmUser(UmUser umUser) {
        this.umUser = umUser;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public String getLocationAddress() {
        return this.locationAddress;
    }
    
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getLandPhoneNumber() {
        return this.landPhoneNumber;
    }
    
    public void setLandPhoneNumber(String landPhoneNumber) {
        this.landPhoneNumber = landPhoneNumber;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<LmLocationsHasUmUser> getLmLocationsHasUmUsers() {
        return this.lmLocationsHasUmUsers;
    }
    
    public void setLmLocationsHasUmUsers(Set<LmLocationsHasUmUser> lmLocationsHasUmUsers) {
        this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
    }
    public Set<UmCustomer> getUmCustomers() {
        return this.umCustomers;
    }
    
    public void setUmCustomers(Set<UmCustomer> umCustomers) {
        this.umCustomers = umCustomers;
    }
    public Set<TmTickets> getTmTicketses() {
        return this.tmTicketses;
    }
    
    public void setTmTicketses(Set<TmTickets> tmTicketses) {
        this.tmTicketses = tmTicketses;
    }
    public Set<LmLocationHistory> getLmLocationHistories() {
        return this.lmLocationHistories;
    }
    
    public void setLmLocationHistories(Set<LmLocationHistory> lmLocationHistories) {
        this.lmLocationHistories = lmLocationHistories;
    }




}


