package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PmInterfaceTopic generated by hbm2java
 */
public class PmInterfaceTopic  implements java.io.Serializable {


     private Integer id;
     private UmUser umUserByCreatedBy;
     private UmUser umUserByUpdatedBy;
     private String topicName;
     private String menuIcon;
     private String sectionClass;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private Set<PmInterface> pmInterfaces = new HashSet<PmInterface>(0);
     private Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopics = new HashSet<UmUserHasInterfaceTopic>(0);

    public PmInterfaceTopic() {
    }

	
    public PmInterfaceTopic(UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public PmInterfaceTopic(UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy, String topicName, String menuIcon, String sectionClass, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, Set<PmInterface> pmInterfaces, Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopics) {
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.umUserByUpdatedBy = umUserByUpdatedBy;
       this.topicName = topicName;
       this.menuIcon = menuIcon;
       this.sectionClass = sectionClass;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.pmInterfaces = pmInterfaces;
       this.umUserHasInterfaceTopics = umUserHasInterfaceTopics;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public UmUser getUmUserByUpdatedBy() {
        return this.umUserByUpdatedBy;
    }
    
    public void setUmUserByUpdatedBy(UmUser umUserByUpdatedBy) {
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public String getTopicName() {
        return this.topicName;
    }
    
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }
    public String getMenuIcon() {
        return this.menuIcon;
    }
    
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }
    public String getSectionClass() {
        return this.sectionClass;
    }
    
    public void setSectionClass(String sectionClass) {
        this.sectionClass = sectionClass;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public Set<PmInterface> getPmInterfaces() {
        return this.pmInterfaces;
    }
    
    public void setPmInterfaces(Set<PmInterface> pmInterfaces) {
        this.pmInterfaces = pmInterfaces;
    }
    public Set<UmUserHasInterfaceTopic> getUmUserHasInterfaceTopics() {
        return this.umUserHasInterfaceTopics;
    }
    
    public void setUmUserHasInterfaceTopics(Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopics) {
        this.umUserHasInterfaceTopics = umUserHasInterfaceTopics;
    }




}


