package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PmInterfaceComponentHistory generated by hbm2java
 */
public class PmInterfaceComponentHistory  implements java.io.Serializable {


     private Integer id;
     private PmInterfaceComponent pmInterfaceComponent;
     private PmUserRole pmUserRole;
     private UmUser umUserByCreatedBy;
     private UmUser umUserByUmUserId;
     private Date createdDate;
     private String interfaceName;
     private String componentName;
     private Boolean isAdded;
     private Boolean isRemoved;

    public PmInterfaceComponentHistory() {
    }

	
    public PmInterfaceComponentHistory(PmInterfaceComponent pmInterfaceComponent, UmUser umUserByCreatedBy) {
        this.pmInterfaceComponent = pmInterfaceComponent;
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public PmInterfaceComponentHistory(PmInterfaceComponent pmInterfaceComponent, PmUserRole pmUserRole, UmUser umUserByCreatedBy, UmUser umUserByUmUserId, Date createdDate, String interfaceName, String componentName, Boolean isAdded, Boolean isRemoved) {
       this.pmInterfaceComponent = pmInterfaceComponent;
       this.pmUserRole = pmUserRole;
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.umUserByUmUserId = umUserByUmUserId;
       this.createdDate = createdDate;
       this.interfaceName = interfaceName;
       this.componentName = componentName;
       this.isAdded = isAdded;
       this.isRemoved = isRemoved;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PmInterfaceComponent getPmInterfaceComponent() {
        return this.pmInterfaceComponent;
    }
    
    public void setPmInterfaceComponent(PmInterfaceComponent pmInterfaceComponent) {
        this.pmInterfaceComponent = pmInterfaceComponent;
    }
    public PmUserRole getPmUserRole() {
        return this.pmUserRole;
    }
    
    public void setPmUserRole(PmUserRole pmUserRole) {
        this.pmUserRole = pmUserRole;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public UmUser getUmUserByUmUserId() {
        return this.umUserByUmUserId;
    }
    
    public void setUmUserByUmUserId(UmUser umUserByUmUserId) {
        this.umUserByUmUserId = umUserByUmUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }
    public String getComponentName() {
        return this.componentName;
    }
    
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }
    public Boolean getIsAdded() {
        return this.isAdded;
    }
    
    public void setIsAdded(Boolean isAdded) {
        this.isAdded = isAdded;
    }
    public Boolean getIsRemoved() {
        return this.isRemoved;
    }
    
    public void setIsRemoved(Boolean isRemoved) {
        this.isRemoved = isRemoved;
    }




}


