package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PmInterface generated by hbm2java
 */
public class PmInterface  implements java.io.Serializable {


     private Integer id;
     private PmInterfaceTopic pmInterfaceTopic;
     private UmUser umUserByUpdatedBy;
     private UmUser umUserByCreatedBy;
     private String interfaceName;
     private String path;
     private String iconClass;
     private String tileClass;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private Set<PmInterfaceComponent> pmInterfaceComponents = new HashSet<PmInterfaceComponent>(0);

    public PmInterface() {
    }

	
    public PmInterface(PmInterfaceTopic pmInterfaceTopic, UmUser umUserByUpdatedBy, UmUser umUserByCreatedBy) {
        this.pmInterfaceTopic = pmInterfaceTopic;
        this.umUserByUpdatedBy = umUserByUpdatedBy;
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public PmInterface(PmInterfaceTopic pmInterfaceTopic, UmUser umUserByUpdatedBy, UmUser umUserByCreatedBy, String interfaceName, String path, String iconClass, String tileClass, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, Set<PmInterfaceComponent> pmInterfaceComponents) {
       this.pmInterfaceTopic = pmInterfaceTopic;
       this.umUserByUpdatedBy = umUserByUpdatedBy;
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.interfaceName = interfaceName;
       this.path = path;
       this.iconClass = iconClass;
       this.tileClass = tileClass;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.pmInterfaceComponents = pmInterfaceComponents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PmInterfaceTopic getPmInterfaceTopic() {
        return this.pmInterfaceTopic;
    }
    
    public void setPmInterfaceTopic(PmInterfaceTopic pmInterfaceTopic) {
        this.pmInterfaceTopic = pmInterfaceTopic;
    }
    public UmUser getUmUserByUpdatedBy() {
        return this.umUserByUpdatedBy;
    }
    
    public void setUmUserByUpdatedBy(UmUser umUserByUpdatedBy) {
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getIconClass() {
        return this.iconClass;
    }
    
    public void setIconClass(String iconClass) {
        this.iconClass = iconClass;
    }
    public String getTileClass() {
        return this.tileClass;
    }
    
    public void setTileClass(String tileClass) {
        this.tileClass = tileClass;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public Set<PmInterfaceComponent> getPmInterfaceComponents() {
        return this.pmInterfaceComponents;
    }
    
    public void setPmInterfaceComponents(Set<PmInterfaceComponent> pmInterfaceComponents) {
        this.pmInterfaceComponents = pmInterfaceComponents;
    }




}


