package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PmUserRoleHasInterfaceComponent generated by hbm2java
 */
public class PmUserRoleHasInterfaceComponent  implements java.io.Serializable {


     private PmUserRoleHasInterfaceComponentId id;
     private PmInterfaceComponent pmInterfaceComponent;
     private PmUserRole pmUserRole;
     private UmUser umUserByUpdatedBy;
     private UmUser umUserByCreatedBy;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;

    public PmUserRoleHasInterfaceComponent() {
    }

	
    public PmUserRoleHasInterfaceComponent(PmUserRoleHasInterfaceComponentId id, PmInterfaceComponent pmInterfaceComponent, PmUserRole pmUserRole, UmUser umUserByUpdatedBy, UmUser umUserByCreatedBy) {
        this.id = id;
        this.pmInterfaceComponent = pmInterfaceComponent;
        this.pmUserRole = pmUserRole;
        this.umUserByUpdatedBy = umUserByUpdatedBy;
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public PmUserRoleHasInterfaceComponent(PmUserRoleHasInterfaceComponentId id, PmInterfaceComponent pmInterfaceComponent, PmUserRole pmUserRole, UmUser umUserByUpdatedBy, UmUser umUserByCreatedBy, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2) {
       this.id = id;
       this.pmInterfaceComponent = pmInterfaceComponent;
       this.pmUserRole = pmUserRole;
       this.umUserByUpdatedBy = umUserByUpdatedBy;
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public PmUserRoleHasInterfaceComponentId getId() {
        return this.id;
    }
    
    public void setId(PmUserRoleHasInterfaceComponentId id) {
        this.id = id;
    }
    public PmInterfaceComponent getPmInterfaceComponent() {
        return this.pmInterfaceComponent;
    }
    
    public void setPmInterfaceComponent(PmInterfaceComponent pmInterfaceComponent) {
        this.pmInterfaceComponent = pmInterfaceComponent;
    }
    public PmUserRole getPmUserRole() {
        return this.pmUserRole;
    }
    
    public void setPmUserRole(PmUserRole pmUserRole) {
        this.pmUserRole = pmUserRole;
    }
    public UmUser getUmUserByUpdatedBy() {
        return this.umUserByUpdatedBy;
    }
    
    public void setUmUserByUpdatedBy(UmUser umUserByUpdatedBy) {
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


