package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QmCategories generated by hbm2java
 */
public class QmCategories  implements java.io.Serializable {


     private Integer id;
     private QmQueue qmQueue;
     private String categoryName;
     private String description;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private Set<QmCategoriesHasSubCategories> qmCategoriesHasSubCategorieses = new HashSet<QmCategoriesHasSubCategories>(0);
     private Set<QmSubCategories> qmSubCategorieses = new HashSet<QmSubCategories>(0);
     private Set<TmTickets> tmTicketses = new HashSet<TmTickets>(0);
     private Set<QmQueueHasCategories> qmQueueHasCategorieses = new HashSet<QmQueueHasCategories>(0);
     private Set<QmCategoriesHasUser> qmCategoriesHasUsers = new HashSet<QmCategoriesHasUser>(0);

    public QmCategories() {
    }

	
    public QmCategories(QmQueue qmQueue, int createdBy, int updatedBy) {
        this.qmQueue = qmQueue;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public QmCategories(QmQueue qmQueue, String categoryName, String description, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy, Set<QmCategoriesHasSubCategories> qmCategoriesHasSubCategorieses, Set<QmSubCategories> qmSubCategorieses, Set<TmTickets> tmTicketses, Set<QmQueueHasCategories> qmQueueHasCategorieses, Set<QmCategoriesHasUser> qmCategoriesHasUsers) {
       this.qmQueue = qmQueue;
       this.categoryName = categoryName;
       this.description = description;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.qmCategoriesHasSubCategorieses = qmCategoriesHasSubCategorieses;
       this.qmSubCategorieses = qmSubCategorieses;
       this.tmTicketses = tmTicketses;
       this.qmQueueHasCategorieses = qmQueueHasCategorieses;
       this.qmCategoriesHasUsers = qmCategoriesHasUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public QmQueue getQmQueue() {
        return this.qmQueue;
    }
    
    public void setQmQueue(QmQueue qmQueue) {
        this.qmQueue = qmQueue;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<QmCategoriesHasSubCategories> getQmCategoriesHasSubCategorieses() {
        return this.qmCategoriesHasSubCategorieses;
    }
    
    public void setQmCategoriesHasSubCategorieses(Set<QmCategoriesHasSubCategories> qmCategoriesHasSubCategorieses) {
        this.qmCategoriesHasSubCategorieses = qmCategoriesHasSubCategorieses;
    }
    public Set<QmSubCategories> getQmSubCategorieses() {
        return this.qmSubCategorieses;
    }
    
    public void setQmSubCategorieses(Set<QmSubCategories> qmSubCategorieses) {
        this.qmSubCategorieses = qmSubCategorieses;
    }
    public Set<TmTickets> getTmTicketses() {
        return this.tmTicketses;
    }
    
    public void setTmTicketses(Set<TmTickets> tmTicketses) {
        this.tmTicketses = tmTicketses;
    }
    public Set<QmQueueHasCategories> getQmQueueHasCategorieses() {
        return this.qmQueueHasCategorieses;
    }
    
    public void setQmQueueHasCategorieses(Set<QmQueueHasCategories> qmQueueHasCategorieses) {
        this.qmQueueHasCategorieses = qmQueueHasCategorieses;
    }
    public Set<QmCategoriesHasUser> getQmCategoriesHasUsers() {
        return this.qmCategoriesHasUsers;
    }
    
    public void setQmCategoriesHasUsers(Set<QmCategoriesHasUser> qmCategoriesHasUsers) {
        this.qmCategoriesHasUsers = qmCategoriesHasUsers;
    }




}


