package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QmQueue generated by hbm2java
 */
public class QmQueue  implements java.io.Serializable {


     private Integer id;
     private String queueName;
     private String description;
     private String backgroundImage;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private String queueIcon;
     private String queueColor;
     private Set<QmQueueHasCategories> qmQueueHasCategorieses = new HashSet<QmQueueHasCategories>(0);
     private Set<TmTickets> tmTicketses = new HashSet<TmTickets>(0);
     private Set<QmCategories> qmCategorieses = new HashSet<QmCategories>(0);
     private Set<QmQueueHasUser> qmQueueHasUsers = new HashSet<QmQueueHasUser>(0);
     private Set<QmQueueHasQuestion> qmQueueHasQuestions = new HashSet<QmQueueHasQuestion>(0);

    public QmQueue() {
    }

	
    public QmQueue(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public QmQueue(String queueName, String description, String backgroundImage, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy, String queueIcon, String queueColor, Set<QmQueueHasCategories> qmQueueHasCategorieses, Set<TmTickets> tmTicketses, Set<QmCategories> qmCategorieses, Set<QmQueueHasUser> qmQueueHasUsers, Set<QmQueueHasQuestion> qmQueueHasQuestions) {
       this.queueName = queueName;
       this.description = description;
       this.backgroundImage = backgroundImage;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.queueIcon = queueIcon;
       this.queueColor = queueColor;
       this.qmQueueHasCategorieses = qmQueueHasCategorieses;
       this.tmTicketses = tmTicketses;
       this.qmCategorieses = qmCategorieses;
       this.qmQueueHasUsers = qmQueueHasUsers;
       this.qmQueueHasQuestions = qmQueueHasQuestions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getQueueName() {
        return this.queueName;
    }
    
    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBackgroundImage() {
        return this.backgroundImage;
    }
    
    public void setBackgroundImage(String backgroundImage) {
        this.backgroundImage = backgroundImage;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getQueueIcon() {
        return this.queueIcon;
    }
    
    public void setQueueIcon(String queueIcon) {
        this.queueIcon = queueIcon;
    }
    public String getQueueColor() {
        return this.queueColor;
    }
    
    public void setQueueColor(String queueColor) {
        this.queueColor = queueColor;
    }
    public Set<QmQueueHasCategories> getQmQueueHasCategorieses() {
        return this.qmQueueHasCategorieses;
    }
    
    public void setQmQueueHasCategorieses(Set<QmQueueHasCategories> qmQueueHasCategorieses) {
        this.qmQueueHasCategorieses = qmQueueHasCategorieses;
    }
    public Set<TmTickets> getTmTicketses() {
        return this.tmTicketses;
    }
    
    public void setTmTicketses(Set<TmTickets> tmTicketses) {
        this.tmTicketses = tmTicketses;
    }
    public Set<QmCategories> getQmCategorieses() {
        return this.qmCategorieses;
    }
    
    public void setQmCategorieses(Set<QmCategories> qmCategorieses) {
        this.qmCategorieses = qmCategorieses;
    }
    public Set<QmQueueHasUser> getQmQueueHasUsers() {
        return this.qmQueueHasUsers;
    }
    
    public void setQmQueueHasUsers(Set<QmQueueHasUser> qmQueueHasUsers) {
        this.qmQueueHasUsers = qmQueueHasUsers;
    }
    public Set<QmQueueHasQuestion> getQmQueueHasQuestions() {
        return this.qmQueueHasQuestions;
    }
    
    public void setQmQueueHasQuestions(Set<QmQueueHasQuestion> qmQueueHasQuestions) {
        this.qmQueueHasQuestions = qmQueueHasQuestions;
    }




}


