package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1



/**
 * QmQueueHasUserId generated by hbm2java
 */
public class QmQueueHasUserId  implements java.io.Serializable {


     private int qmQueueId;
     private int umUserId;

    public QmQueueHasUserId() {
    }

    public QmQueueHasUserId(int qmQueueId, int umUserId) {
       this.qmQueueId = qmQueueId;
       this.umUserId = umUserId;
    }
   
    public int getQmQueueId() {
        return this.qmQueueId;
    }
    
    public void setQmQueueId(int qmQueueId) {
        this.qmQueueId = qmQueueId;
    }
    public int getUmUserId() {
        return this.umUserId;
    }
    
    public void setUmUserId(int umUserId) {
        this.umUserId = umUserId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QmQueueHasUserId) ) return false;
		 QmQueueHasUserId castOther = ( QmQueueHasUserId ) other; 
         
		 return (this.getQmQueueId()==castOther.getQmQueueId())
 && (this.getUmUserId()==castOther.getUmUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQmQueueId();
         result = 37 * result + this.getUmUserId();
         return result;
   }   


}


