package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RcasAnswers generated by hbm2java
 */
public class RcasAnswers  implements java.io.Serializable {


     private Integer id;
     private String answer;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private Set<TmTicketHasQueueHasQuestionHasAnswers> tmTicketHasQueueHasQuestionHasAnswerses = new HashSet<TmTicketHasQueueHasQuestionHasAnswers>(0);

    public RcasAnswers() {
    }

	
    public RcasAnswers(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public RcasAnswers(String answer, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy, Set<TmTicketHasQueueHasQuestionHasAnswers> tmTicketHasQueueHasQuestionHasAnswerses) {
       this.answer = answer;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.tmTicketHasQueueHasQuestionHasAnswerses = tmTicketHasQueueHasQuestionHasAnswerses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<TmTicketHasQueueHasQuestionHasAnswers> getTmTicketHasQueueHasQuestionHasAnswerses() {
        return this.tmTicketHasQueueHasQuestionHasAnswerses;
    }
    
    public void setTmTicketHasQueueHasQuestionHasAnswerses(Set<TmTicketHasQueueHasQuestionHasAnswers> tmTicketHasQueueHasQuestionHasAnswerses) {
        this.tmTicketHasQueueHasQuestionHasAnswerses = tmTicketHasQueueHasQuestionHasAnswerses;
    }




}


