package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmSessionActivity generated by hbm2java
 */
public class SmSessionActivity  implements java.io.Serializable {


     private Integer id;
     private SmSession smSession;
     private UmUser umUser;
     private String description;
     private Date createdAt;
     private String activityType;
     private String activityTopic;
     private Integer activityId;
     private String remark1;
     private String remark2;

    public SmSessionActivity() {
    }

	
    public SmSessionActivity(SmSession smSession, UmUser umUser) {
        this.smSession = smSession;
        this.umUser = umUser;
    }
    public SmSessionActivity(SmSession smSession, UmUser umUser, String description, Date createdAt, String activityType, String activityTopic, Integer activityId, String remark1, String remark2) {
       this.smSession = smSession;
       this.umUser = umUser;
       this.description = description;
       this.createdAt = createdAt;
       this.activityType = activityType;
       this.activityTopic = activityTopic;
       this.activityId = activityId;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SmSession getSmSession() {
        return this.smSession;
    }
    
    public void setSmSession(SmSession smSession) {
        this.smSession = smSession;
    }
    public UmUser getUmUser() {
        return this.umUser;
    }
    
    public void setUmUser(UmUser umUser) {
        this.umUser = umUser;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getActivityType() {
        return this.activityType;
    }
    
    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }
    public String getActivityTopic() {
        return this.activityTopic;
    }
    
    public void setActivityTopic(String activityTopic) {
        this.activityTopic = activityTopic;
    }
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


