package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SmSession generated by hbm2java
 */
public class SmSession  implements java.io.Serializable {


     private Integer id;
     private UmUser umUser;
     private String ipAddress;
     private Date timeIn;
     private Date timeOut;
     private Boolean isActive;
     private Date createdAt;
     private Date updatedAt;
     private Set<SmSessionActivity> smSessionActivities = new HashSet<SmSessionActivity>(0);

    public SmSession() {
    }

	
    public SmSession(UmUser umUser) {
        this.umUser = umUser;
    }
    public SmSession(UmUser umUser, String ipAddress, Date timeIn, Date timeOut, Boolean isActive, Date createdAt, Date updatedAt, Set<SmSessionActivity> smSessionActivities) {
       this.umUser = umUser;
       this.ipAddress = ipAddress;
       this.timeIn = timeIn;
       this.timeOut = timeOut;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.smSessionActivities = smSessionActivities;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UmUser getUmUser() {
        return this.umUser;
    }
    
    public void setUmUser(UmUser umUser) {
        this.umUser = umUser;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getTimeIn() {
        return this.timeIn;
    }
    
    public void setTimeIn(Date timeIn) {
        this.timeIn = timeIn;
    }
    public Date getTimeOut() {
        return this.timeOut;
    }
    
    public void setTimeOut(Date timeOut) {
        this.timeOut = timeOut;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set<SmSessionActivity> getSmSessionActivities() {
        return this.smSessionActivities;
    }
    
    public void setSmSessionActivities(Set<SmSessionActivity> smSessionActivities) {
        this.smSessionActivities = smSessionActivities;
    }




}


