package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UmCustomer generated by hbm2java
 */
public class UmCustomer  implements java.io.Serializable {


     private Integer id;
     private LmLocations lmLocations;
     private String customerName;
     private String address;
     private String mobileNumber;
     private Byte isVerified;
     private Integer otp;
     private String emailAddress;
     private String nic;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private Set<TmTickets> tmTicketses = new HashSet<TmTickets>(0);

    public UmCustomer() {
    }

	
    public UmCustomer(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public UmCustomer(LmLocations lmLocations, String customerName, String address, String mobileNumber, Byte isVerified, Integer otp, String emailAddress, String nic, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy, Set<TmTickets> tmTicketses) {
       this.lmLocations = lmLocations;
       this.customerName = customerName;
       this.address = address;
       this.mobileNumber = mobileNumber;
       this.isVerified = isVerified;
       this.otp = otp;
       this.emailAddress = emailAddress;
       this.nic = nic;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.tmTicketses = tmTicketses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LmLocations getLmLocations() {
        return this.lmLocations;
    }
    
    public void setLmLocations(LmLocations lmLocations) {
        this.lmLocations = lmLocations;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public Byte getIsVerified() {
        return this.isVerified;
    }
    
    public void setIsVerified(Byte isVerified) {
        this.isVerified = isVerified;
    }
    public Integer getOtp() {
        return this.otp;
    }
    
    public void setOtp(Integer otp) {
        this.otp = otp;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set<TmTickets> getTmTicketses() {
        return this.tmTicketses;
    }
    
    public void setTmTicketses(Set<TmTickets> tmTicketses) {
        this.tmTicketses = tmTicketses;
    }




}


