package com.it.db;
// Generated May 31, 2022 9:18:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UmUser generated by hbm2java
 */
public class UmUser  implements java.io.Serializable {


     private Integer id;
     private PmUserRole pmUserRole;
     private String firstName;
     private String lastName;
     private Byte status;
     private Date createdAt;
     private Date updatedAt;
     private String userName;
     private String password;
     private String nicOrPassport;
     private Date dateOfBirth;
     private String mobileNumber;
     private String emailAddress;
     private Byte gender;
     private String maritialStatus;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private String passport;
     private String remark3;
     private String remark4;
     private Set<PmInterfaceComponent> pmInterfaceComponentsForCreatedBy = new HashSet<PmInterfaceComponent>(0);
     private Set<QmCategoriesHasUser> qmCategoriesHasUsers = new HashSet<QmCategoriesHasUser>(0);
     private Set<PmInterfaceComponent> pmInterfaceComponentsForUpdatedBy = new HashSet<PmInterfaceComponent>(0);
     private Set<SmSession> smSessions = new HashSet<SmSession>(0);
     private Set<PmInterface> pmInterfacesForUpdatedBy = new HashSet<PmInterface>(0);
     private Set<PmInterface> pmInterfacesForCreatedBy = new HashSet<PmInterface>(0);
     private Set<LmLocationsHasUmUser> lmLocationsHasUmUsers = new HashSet<LmLocationsHasUmUser>(0);
     private Set<SmSessionActivity> smSessionActivities = new HashSet<SmSessionActivity>(0);
     private Set<QmQueueHasUser> qmQueueHasUsers = new HashSet<QmQueueHasUser>(0);
     private Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForCreatedBy = new HashSet<PmInterfaceComponentHistory>(0);
     private Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForUmUserId = new HashSet<PmInterfaceComponentHistory>(0);
     private Set<PmUserRole> pmUserRolesForCreatedBy = new HashSet<PmUserRole>(0);
     private Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForCreatedBy = new HashSet<UmUserHasInterfaceTopic>(0);
     private Set<PmUserRole> pmUserRolesForUpdatedBy = new HashSet<PmUserRole>(0);
     private Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUpdatedBy = new HashSet<UmUserHasInterfaceTopic>(0);
     private Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForUpdatedBy = new HashSet<PmUserRoleHasInterfaceComponent>(0);
     private Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForCreatedBy = new HashSet<PmUserRoleHasInterfaceComponent>(0);
     private Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUmUserId = new HashSet<UmUserHasInterfaceTopic>(0);
     private Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForCreatedBy = new HashSet<UmUserHasInterfaceComponent>(0);
     private Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUpdatedBy = new HashSet<UmUserHasInterfaceComponent>(0);
     private Set<LmLocations> lmLocationses = new HashSet<LmLocations>(0);
     private Set<TmTicketsHasUmUser> tmTicketsHasUmUsers = new HashSet<TmTicketsHasUmUser>(0);
     private Set<PmInterfaceTopic> pmInterfaceTopicsForCreatedBy = new HashSet<PmInterfaceTopic>(0);
     private Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUmUserId = new HashSet<UmUserHasInterfaceComponent>(0);
     private Set<PmInterfaceTopic> pmInterfaceTopicsForUpdatedBy = new HashSet<PmInterfaceTopic>(0);
     private Set<QmSubCategoriesHasUser> qmSubCategoriesHasUsers = new HashSet<QmSubCategoriesHasUser>(0);

    public UmUser() {
    }

	
    public UmUser(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public UmUser(PmUserRole pmUserRole, String firstName, String lastName, Byte status, Date createdAt, Date updatedAt, String userName, String password, String nicOrPassport, Date dateOfBirth, String mobileNumber, String emailAddress, Byte gender, String maritialStatus, String remark1, String remark2, int createdBy, int updatedBy, String passport, String remark3, String remark4, Set<PmInterfaceComponent> pmInterfaceComponentsForCreatedBy, Set<QmCategoriesHasUser> qmCategoriesHasUsers, Set<PmInterfaceComponent> pmInterfaceComponentsForUpdatedBy, Set<SmSession> smSessions, Set<PmInterface> pmInterfacesForUpdatedBy, Set<PmInterface> pmInterfacesForCreatedBy, Set<LmLocationsHasUmUser> lmLocationsHasUmUsers, Set<SmSessionActivity> smSessionActivities, Set<QmQueueHasUser> qmQueueHasUsers, Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForCreatedBy, Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForUmUserId, Set<PmUserRole> pmUserRolesForCreatedBy, Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForCreatedBy, Set<PmUserRole> pmUserRolesForUpdatedBy, Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUpdatedBy, Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForUpdatedBy, Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForCreatedBy, Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUmUserId, Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForCreatedBy, Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUpdatedBy, Set<LmLocations> lmLocationses, Set<TmTicketsHasUmUser> tmTicketsHasUmUsers, Set<PmInterfaceTopic> pmInterfaceTopicsForCreatedBy, Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUmUserId, Set<PmInterfaceTopic> pmInterfaceTopicsForUpdatedBy, Set<QmSubCategoriesHasUser> qmSubCategoriesHasUsers) {
       this.pmUserRole = pmUserRole;
       this.firstName = firstName;
       this.lastName = lastName;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.userName = userName;
       this.password = password;
       this.nicOrPassport = nicOrPassport;
       this.dateOfBirth = dateOfBirth;
       this.mobileNumber = mobileNumber;
       this.emailAddress = emailAddress;
       this.gender = gender;
       this.maritialStatus = maritialStatus;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.passport = passport;
       this.remark3 = remark3;
       this.remark4 = remark4;
       this.pmInterfaceComponentsForCreatedBy = pmInterfaceComponentsForCreatedBy;
       this.qmCategoriesHasUsers = qmCategoriesHasUsers;
       this.pmInterfaceComponentsForUpdatedBy = pmInterfaceComponentsForUpdatedBy;
       this.smSessions = smSessions;
       this.pmInterfacesForUpdatedBy = pmInterfacesForUpdatedBy;
       this.pmInterfacesForCreatedBy = pmInterfacesForCreatedBy;
       this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
       this.smSessionActivities = smSessionActivities;
       this.qmQueueHasUsers = qmQueueHasUsers;
       this.pmInterfaceComponentHistoriesForCreatedBy = pmInterfaceComponentHistoriesForCreatedBy;
       this.pmInterfaceComponentHistoriesForUmUserId = pmInterfaceComponentHistoriesForUmUserId;
       this.pmUserRolesForCreatedBy = pmUserRolesForCreatedBy;
       this.umUserHasInterfaceTopicsForCreatedBy = umUserHasInterfaceTopicsForCreatedBy;
       this.pmUserRolesForUpdatedBy = pmUserRolesForUpdatedBy;
       this.umUserHasInterfaceTopicsForUpdatedBy = umUserHasInterfaceTopicsForUpdatedBy;
       this.pmUserRoleHasInterfaceComponentsForUpdatedBy = pmUserRoleHasInterfaceComponentsForUpdatedBy;
       this.pmUserRoleHasInterfaceComponentsForCreatedBy = pmUserRoleHasInterfaceComponentsForCreatedBy;
       this.umUserHasInterfaceTopicsForUmUserId = umUserHasInterfaceTopicsForUmUserId;
       this.umUserHasInterfaceComponentsForCreatedBy = umUserHasInterfaceComponentsForCreatedBy;
       this.umUserHasInterfaceComponentsForUpdatedBy = umUserHasInterfaceComponentsForUpdatedBy;
       this.lmLocationses = lmLocationses;
       this.tmTicketsHasUmUsers = tmTicketsHasUmUsers;
       this.pmInterfaceTopicsForCreatedBy = pmInterfaceTopicsForCreatedBy;
       this.umUserHasInterfaceComponentsForUmUserId = umUserHasInterfaceComponentsForUmUserId;
       this.pmInterfaceTopicsForUpdatedBy = pmInterfaceTopicsForUpdatedBy;
       this.qmSubCategoriesHasUsers = qmSubCategoriesHasUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PmUserRole getPmUserRole() {
        return this.pmUserRole;
    }
    
    public void setPmUserRole(PmUserRole pmUserRole) {
        this.pmUserRole = pmUserRole;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNicOrPassport() {
        return this.nicOrPassport;
    }
    
    public void setNicOrPassport(String nicOrPassport) {
        this.nicOrPassport = nicOrPassport;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public Byte getGender() {
        return this.gender;
    }
    
    public void setGender(Byte gender) {
        this.gender = gender;
    }
    public String getMaritialStatus() {
        return this.maritialStatus;
    }
    
    public void setMaritialStatus(String maritialStatus) {
        this.maritialStatus = maritialStatus;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getPassport() {
        return this.passport;
    }
    
    public void setPassport(String passport) {
        this.passport = passport;
    }
    public String getRemark3() {
        return this.remark3;
    }
    
    public void setRemark3(String remark3) {
        this.remark3 = remark3;
    }
    public String getRemark4() {
        return this.remark4;
    }
    
    public void setRemark4(String remark4) {
        this.remark4 = remark4;
    }
    public Set<PmInterfaceComponent> getPmInterfaceComponentsForCreatedBy() {
        return this.pmInterfaceComponentsForCreatedBy;
    }
    
    public void setPmInterfaceComponentsForCreatedBy(Set<PmInterfaceComponent> pmInterfaceComponentsForCreatedBy) {
        this.pmInterfaceComponentsForCreatedBy = pmInterfaceComponentsForCreatedBy;
    }
    public Set<QmCategoriesHasUser> getQmCategoriesHasUsers() {
        return this.qmCategoriesHasUsers;
    }
    
    public void setQmCategoriesHasUsers(Set<QmCategoriesHasUser> qmCategoriesHasUsers) {
        this.qmCategoriesHasUsers = qmCategoriesHasUsers;
    }
    public Set<PmInterfaceComponent> getPmInterfaceComponentsForUpdatedBy() {
        return this.pmInterfaceComponentsForUpdatedBy;
    }
    
    public void setPmInterfaceComponentsForUpdatedBy(Set<PmInterfaceComponent> pmInterfaceComponentsForUpdatedBy) {
        this.pmInterfaceComponentsForUpdatedBy = pmInterfaceComponentsForUpdatedBy;
    }
    public Set<SmSession> getSmSessions() {
        return this.smSessions;
    }
    
    public void setSmSessions(Set<SmSession> smSessions) {
        this.smSessions = smSessions;
    }
    public Set<PmInterface> getPmInterfacesForUpdatedBy() {
        return this.pmInterfacesForUpdatedBy;
    }
    
    public void setPmInterfacesForUpdatedBy(Set<PmInterface> pmInterfacesForUpdatedBy) {
        this.pmInterfacesForUpdatedBy = pmInterfacesForUpdatedBy;
    }
    public Set<PmInterface> getPmInterfacesForCreatedBy() {
        return this.pmInterfacesForCreatedBy;
    }
    
    public void setPmInterfacesForCreatedBy(Set<PmInterface> pmInterfacesForCreatedBy) {
        this.pmInterfacesForCreatedBy = pmInterfacesForCreatedBy;
    }
    public Set<LmLocationsHasUmUser> getLmLocationsHasUmUsers() {
        return this.lmLocationsHasUmUsers;
    }
    
    public void setLmLocationsHasUmUsers(Set<LmLocationsHasUmUser> lmLocationsHasUmUsers) {
        this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
    }
    public Set<SmSessionActivity> getSmSessionActivities() {
        return this.smSessionActivities;
    }
    
    public void setSmSessionActivities(Set<SmSessionActivity> smSessionActivities) {
        this.smSessionActivities = smSessionActivities;
    }
    public Set<QmQueueHasUser> getQmQueueHasUsers() {
        return this.qmQueueHasUsers;
    }
    
    public void setQmQueueHasUsers(Set<QmQueueHasUser> qmQueueHasUsers) {
        this.qmQueueHasUsers = qmQueueHasUsers;
    }
    public Set<PmInterfaceComponentHistory> getPmInterfaceComponentHistoriesForCreatedBy() {
        return this.pmInterfaceComponentHistoriesForCreatedBy;
    }
    
    public void setPmInterfaceComponentHistoriesForCreatedBy(Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForCreatedBy) {
        this.pmInterfaceComponentHistoriesForCreatedBy = pmInterfaceComponentHistoriesForCreatedBy;
    }
    public Set<PmInterfaceComponentHistory> getPmInterfaceComponentHistoriesForUmUserId() {
        return this.pmInterfaceComponentHistoriesForUmUserId;
    }
    
    public void setPmInterfaceComponentHistoriesForUmUserId(Set<PmInterfaceComponentHistory> pmInterfaceComponentHistoriesForUmUserId) {
        this.pmInterfaceComponentHistoriesForUmUserId = pmInterfaceComponentHistoriesForUmUserId;
    }
    public Set<PmUserRole> getPmUserRolesForCreatedBy() {
        return this.pmUserRolesForCreatedBy;
    }
    
    public void setPmUserRolesForCreatedBy(Set<PmUserRole> pmUserRolesForCreatedBy) {
        this.pmUserRolesForCreatedBy = pmUserRolesForCreatedBy;
    }
    public Set<UmUserHasInterfaceTopic> getUmUserHasInterfaceTopicsForCreatedBy() {
        return this.umUserHasInterfaceTopicsForCreatedBy;
    }
    
    public void setUmUserHasInterfaceTopicsForCreatedBy(Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForCreatedBy) {
        this.umUserHasInterfaceTopicsForCreatedBy = umUserHasInterfaceTopicsForCreatedBy;
    }
    public Set<PmUserRole> getPmUserRolesForUpdatedBy() {
        return this.pmUserRolesForUpdatedBy;
    }
    
    public void setPmUserRolesForUpdatedBy(Set<PmUserRole> pmUserRolesForUpdatedBy) {
        this.pmUserRolesForUpdatedBy = pmUserRolesForUpdatedBy;
    }
    public Set<UmUserHasInterfaceTopic> getUmUserHasInterfaceTopicsForUpdatedBy() {
        return this.umUserHasInterfaceTopicsForUpdatedBy;
    }
    
    public void setUmUserHasInterfaceTopicsForUpdatedBy(Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUpdatedBy) {
        this.umUserHasInterfaceTopicsForUpdatedBy = umUserHasInterfaceTopicsForUpdatedBy;
    }
    public Set<PmUserRoleHasInterfaceComponent> getPmUserRoleHasInterfaceComponentsForUpdatedBy() {
        return this.pmUserRoleHasInterfaceComponentsForUpdatedBy;
    }
    
    public void setPmUserRoleHasInterfaceComponentsForUpdatedBy(Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForUpdatedBy) {
        this.pmUserRoleHasInterfaceComponentsForUpdatedBy = pmUserRoleHasInterfaceComponentsForUpdatedBy;
    }
    public Set<PmUserRoleHasInterfaceComponent> getPmUserRoleHasInterfaceComponentsForCreatedBy() {
        return this.pmUserRoleHasInterfaceComponentsForCreatedBy;
    }
    
    public void setPmUserRoleHasInterfaceComponentsForCreatedBy(Set<PmUserRoleHasInterfaceComponent> pmUserRoleHasInterfaceComponentsForCreatedBy) {
        this.pmUserRoleHasInterfaceComponentsForCreatedBy = pmUserRoleHasInterfaceComponentsForCreatedBy;
    }
    public Set<UmUserHasInterfaceTopic> getUmUserHasInterfaceTopicsForUmUserId() {
        return this.umUserHasInterfaceTopicsForUmUserId;
    }
    
    public void setUmUserHasInterfaceTopicsForUmUserId(Set<UmUserHasInterfaceTopic> umUserHasInterfaceTopicsForUmUserId) {
        this.umUserHasInterfaceTopicsForUmUserId = umUserHasInterfaceTopicsForUmUserId;
    }
    public Set<UmUserHasInterfaceComponent> getUmUserHasInterfaceComponentsForCreatedBy() {
        return this.umUserHasInterfaceComponentsForCreatedBy;
    }
    
    public void setUmUserHasInterfaceComponentsForCreatedBy(Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForCreatedBy) {
        this.umUserHasInterfaceComponentsForCreatedBy = umUserHasInterfaceComponentsForCreatedBy;
    }
    public Set<UmUserHasInterfaceComponent> getUmUserHasInterfaceComponentsForUpdatedBy() {
        return this.umUserHasInterfaceComponentsForUpdatedBy;
    }
    
    public void setUmUserHasInterfaceComponentsForUpdatedBy(Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUpdatedBy) {
        this.umUserHasInterfaceComponentsForUpdatedBy = umUserHasInterfaceComponentsForUpdatedBy;
    }
    public Set<LmLocations> getLmLocationses() {
        return this.lmLocationses;
    }
    
    public void setLmLocationses(Set<LmLocations> lmLocationses) {
        this.lmLocationses = lmLocationses;
    }
    public Set<TmTicketsHasUmUser> getTmTicketsHasUmUsers() {
        return this.tmTicketsHasUmUsers;
    }
    
    public void setTmTicketsHasUmUsers(Set<TmTicketsHasUmUser> tmTicketsHasUmUsers) {
        this.tmTicketsHasUmUsers = tmTicketsHasUmUsers;
    }
    public Set<PmInterfaceTopic> getPmInterfaceTopicsForCreatedBy() {
        return this.pmInterfaceTopicsForCreatedBy;
    }
    
    public void setPmInterfaceTopicsForCreatedBy(Set<PmInterfaceTopic> pmInterfaceTopicsForCreatedBy) {
        this.pmInterfaceTopicsForCreatedBy = pmInterfaceTopicsForCreatedBy;
    }
    public Set<UmUserHasInterfaceComponent> getUmUserHasInterfaceComponentsForUmUserId() {
        return this.umUserHasInterfaceComponentsForUmUserId;
    }
    
    public void setUmUserHasInterfaceComponentsForUmUserId(Set<UmUserHasInterfaceComponent> umUserHasInterfaceComponentsForUmUserId) {
        this.umUserHasInterfaceComponentsForUmUserId = umUserHasInterfaceComponentsForUmUserId;
    }
    public Set<PmInterfaceTopic> getPmInterfaceTopicsForUpdatedBy() {
        return this.pmInterfaceTopicsForUpdatedBy;
    }
    
    public void setPmInterfaceTopicsForUpdatedBy(Set<PmInterfaceTopic> pmInterfaceTopicsForUpdatedBy) {
        this.pmInterfaceTopicsForUpdatedBy = pmInterfaceTopicsForUpdatedBy;
    }
    public Set<QmSubCategoriesHasUser> getQmSubCategoriesHasUsers() {
        return this.qmSubCategoriesHasUsers;
    }
    
    public void setQmSubCategoriesHasUsers(Set<QmSubCategoriesHasUser> qmSubCategoriesHasUsers) {
        this.qmSubCategoriesHasUsers = qmSubCategoriesHasUsers;
    }




}


