package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1



/**
 * LmLocationsHasUmUserId generated by hbm2java
 */
public class LmLocationsHasUmUserId  implements java.io.Serializable {


     private int lmLocationsId;
     private int umUserId;

    public LmLocationsHasUmUserId() {
    }

    public LmLocationsHasUmUserId(int lmLocationsId, int umUserId) {
       this.lmLocationsId = lmLocationsId;
       this.umUserId = umUserId;
    }
   
    public int getLmLocationsId() {
        return this.lmLocationsId;
    }
    
    public void setLmLocationsId(int lmLocationsId) {
        this.lmLocationsId = lmLocationsId;
    }
    public int getUmUserId() {
        return this.umUserId;
    }
    
    public void setUmUserId(int umUserId) {
        this.umUserId = umUserId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LmLocationsHasUmUserId) ) return false;
		 LmLocationsHasUmUserId castOther = ( LmLocationsHasUmUserId ) other; 
         
		 return (this.getLmLocationsId()==castOther.getLmLocationsId())
 && (this.getUmUserId()==castOther.getUmUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLmLocationsId();
         result = 37 * result + this.getUmUserId();
         return result;
   }   


}


