package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PmInterfaceComponent generated by hbm2java
 */
public class PmInterfaceComponent  implements java.io.Serializable {


     private Integer id;
     private PmInterface pmInterface;
     private UmUser umUserByCreatedBy;
     private UmUser umUserByUpdatedBy;
     private String componentName;
     private String componentId;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private Set pmUserRoleHasInterfaceComponents = new HashSet(0);
     private Set umUserHasInterfaceComponents = new HashSet(0);
     private Set pmInterfaceComponentHistories = new HashSet(0);

    public PmInterfaceComponent() {
    }

	
    public PmInterfaceComponent(PmInterface pmInterface, UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy) {
        this.pmInterface = pmInterface;
        this.umUserByCreatedBy = umUserByCreatedBy;
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public PmInterfaceComponent(PmInterface pmInterface, UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy, String componentName, String componentId, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, Set pmUserRoleHasInterfaceComponents, Set umUserHasInterfaceComponents, Set pmInterfaceComponentHistories) {
       this.pmInterface = pmInterface;
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.umUserByUpdatedBy = umUserByUpdatedBy;
       this.componentName = componentName;
       this.componentId = componentId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.pmUserRoleHasInterfaceComponents = pmUserRoleHasInterfaceComponents;
       this.umUserHasInterfaceComponents = umUserHasInterfaceComponents;
       this.pmInterfaceComponentHistories = pmInterfaceComponentHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PmInterface getPmInterface() {
        return this.pmInterface;
    }
    
    public void setPmInterface(PmInterface pmInterface) {
        this.pmInterface = pmInterface;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public UmUser getUmUserByUpdatedBy() {
        return this.umUserByUpdatedBy;
    }
    
    public void setUmUserByUpdatedBy(UmUser umUserByUpdatedBy) {
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public String getComponentName() {
        return this.componentName;
    }
    
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }
    public String getComponentId() {
        return this.componentId;
    }
    
    public void setComponentId(String componentId) {
        this.componentId = componentId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public Set getPmUserRoleHasInterfaceComponents() {
        return this.pmUserRoleHasInterfaceComponents;
    }
    
    public void setPmUserRoleHasInterfaceComponents(Set pmUserRoleHasInterfaceComponents) {
        this.pmUserRoleHasInterfaceComponents = pmUserRoleHasInterfaceComponents;
    }
    public Set getUmUserHasInterfaceComponents() {
        return this.umUserHasInterfaceComponents;
    }
    
    public void setUmUserHasInterfaceComponents(Set umUserHasInterfaceComponents) {
        this.umUserHasInterfaceComponents = umUserHasInterfaceComponents;
    }
    public Set getPmInterfaceComponentHistories() {
        return this.pmInterfaceComponentHistories;
    }
    
    public void setPmInterfaceComponentHistories(Set pmInterfaceComponentHistories) {
        this.pmInterfaceComponentHistories = pmInterfaceComponentHistories;
    }




}


