package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PmUserRole generated by hbm2java
 */
public class PmUserRole  implements java.io.Serializable {


     private Integer id;
     private UmUser umUserByCreatedBy;
     private UmUser umUserByUpdatedBy;
     private String userRoleName;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private Set pmInterfaceComponentHistories = new HashSet(0);
     private Set umUsers = new HashSet(0);
     private Set pmUserRoleHasInterfaceComponents = new HashSet(0);

    public PmUserRole() {
    }

	
    public PmUserRole(UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public PmUserRole(UmUser umUserByCreatedBy, UmUser umUserByUpdatedBy, String userRoleName, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, Set pmInterfaceComponentHistories, Set umUsers, Set pmUserRoleHasInterfaceComponents) {
       this.umUserByCreatedBy = umUserByCreatedBy;
       this.umUserByUpdatedBy = umUserByUpdatedBy;
       this.userRoleName = userRoleName;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.pmInterfaceComponentHistories = pmInterfaceComponentHistories;
       this.umUsers = umUsers;
       this.pmUserRoleHasInterfaceComponents = pmUserRoleHasInterfaceComponents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UmUser getUmUserByCreatedBy() {
        return this.umUserByCreatedBy;
    }
    
    public void setUmUserByCreatedBy(UmUser umUserByCreatedBy) {
        this.umUserByCreatedBy = umUserByCreatedBy;
    }
    public UmUser getUmUserByUpdatedBy() {
        return this.umUserByUpdatedBy;
    }
    
    public void setUmUserByUpdatedBy(UmUser umUserByUpdatedBy) {
        this.umUserByUpdatedBy = umUserByUpdatedBy;
    }
    public String getUserRoleName() {
        return this.userRoleName;
    }
    
    public void setUserRoleName(String userRoleName) {
        this.userRoleName = userRoleName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public Set getPmInterfaceComponentHistories() {
        return this.pmInterfaceComponentHistories;
    }
    
    public void setPmInterfaceComponentHistories(Set pmInterfaceComponentHistories) {
        this.pmInterfaceComponentHistories = pmInterfaceComponentHistories;
    }
    public Set getUmUsers() {
        return this.umUsers;
    }
    
    public void setUmUsers(Set umUsers) {
        this.umUsers = umUsers;
    }
    public Set getPmUserRoleHasInterfaceComponents() {
        return this.pmUserRoleHasInterfaceComponents;
    }
    
    public void setPmUserRoleHasInterfaceComponents(Set pmUserRoleHasInterfaceComponents) {
        this.pmUserRoleHasInterfaceComponents = pmUserRoleHasInterfaceComponents;
    }




}


