package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1



/**
 * QmQueueHasCategoriesId generated by hbm2java
 */
public class QmQueueHasCategoriesId  implements java.io.Serializable {


     private int qmQueueId;
     private int qmCategoriesId;

    public QmQueueHasCategoriesId() {
    }

    public QmQueueHasCategoriesId(int qmQueueId, int qmCategoriesId) {
       this.qmQueueId = qmQueueId;
       this.qmCategoriesId = qmCategoriesId;
    }
   
    public int getQmQueueId() {
        return this.qmQueueId;
    }
    
    public void setQmQueueId(int qmQueueId) {
        this.qmQueueId = qmQueueId;
    }
    public int getQmCategoriesId() {
        return this.qmCategoriesId;
    }
    
    public void setQmCategoriesId(int qmCategoriesId) {
        this.qmCategoriesId = qmCategoriesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QmQueueHasCategoriesId) ) return false;
		 QmQueueHasCategoriesId castOther = ( QmQueueHasCategoriesId ) other; 
         
		 return (this.getQmQueueId()==castOther.getQmQueueId())
 && (this.getQmCategoriesId()==castOther.getQmCategoriesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQmQueueId();
         result = 37 * result + this.getQmCategoriesId();
         return result;
   }   


}


