package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RcasQuestion generated by hbm2java
 */
public class RcasQuestion  implements java.io.Serializable {


     private Integer id;
     private String questionName;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private Set qmQueueHasQuestions = new HashSet(0);

    public RcasQuestion() {
    }

	
    public RcasQuestion(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public RcasQuestion(String questionName, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy, Set qmQueueHasQuestions) {
       this.questionName = questionName;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.qmQueueHasQuestions = qmQueueHasQuestions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getQuestionName() {
        return this.questionName;
    }
    
    public void setQuestionName(String questionName) {
        this.questionName = questionName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Set getQmQueueHasQuestions() {
        return this.qmQueueHasQuestions;
    }
    
    public void setQmQueueHasQuestions(Set qmQueueHasQuestions) {
        this.qmQueueHasQuestions = qmQueueHasQuestions;
    }




}


