package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TmTicketHasQueueHasQuestionHasAnswers generated by hbm2java
 */
public class TmTicketHasQueueHasQuestionHasAnswers  implements java.io.Serializable {


     private TmTicketHasQueueHasQuestionHasAnswersId id;
     private QmQueueHasQuestion qmQueueHasQuestion;
     private RcasAnswers rcasAnswers;
     private TmTickets tmTickets;
     private Date createdAt;
     private Date updatedAt;
     private Byte status;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;

    public TmTicketHasQueueHasQuestionHasAnswers() {
    }

	
    public TmTicketHasQueueHasQuestionHasAnswers(TmTicketHasQueueHasQuestionHasAnswersId id, QmQueueHasQuestion qmQueueHasQuestion, RcasAnswers rcasAnswers, TmTickets tmTickets, int createdBy, int updatedBy) {
        this.id = id;
        this.qmQueueHasQuestion = qmQueueHasQuestion;
        this.rcasAnswers = rcasAnswers;
        this.tmTickets = tmTickets;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public TmTicketHasQueueHasQuestionHasAnswers(TmTicketHasQueueHasQuestionHasAnswersId id, QmQueueHasQuestion qmQueueHasQuestion, RcasAnswers rcasAnswers, TmTickets tmTickets, Date createdAt, Date updatedAt, Byte status, String remark1, String remark2, int createdBy, int updatedBy) {
       this.id = id;
       this.qmQueueHasQuestion = qmQueueHasQuestion;
       this.rcasAnswers = rcasAnswers;
       this.tmTickets = tmTickets;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.status = status;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    public TmTicketHasQueueHasQuestionHasAnswersId getId() {
        return this.id;
    }
    
    public void setId(TmTicketHasQueueHasQuestionHasAnswersId id) {
        this.id = id;
    }
    public QmQueueHasQuestion getQmQueueHasQuestion() {
        return this.qmQueueHasQuestion;
    }
    
    public void setQmQueueHasQuestion(QmQueueHasQuestion qmQueueHasQuestion) {
        this.qmQueueHasQuestion = qmQueueHasQuestion;
    }
    public RcasAnswers getRcasAnswers() {
        return this.rcasAnswers;
    }
    
    public void setRcasAnswers(RcasAnswers rcasAnswers) {
        this.rcasAnswers = rcasAnswers;
    }
    public TmTickets getTmTickets() {
        return this.tmTickets;
    }
    
    public void setTmTickets(TmTickets tmTickets) {
        this.tmTickets = tmTickets;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }




}


