package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1



/**
 * TmTicketHasQueueHasQuestionHasAnswersId generated by hbm2java
 */
public class TmTicketHasQueueHasQuestionHasAnswersId  implements java.io.Serializable {


     private int qmQueueHasQuestionQmQueueId;
     private int qmQueueHasQuestionRcasQuestionId;
     private int rcasAnswersId;
     private int tmTicketsId;

    public TmTicketHasQueueHasQuestionHasAnswersId() {
    }

    public TmTicketHasQueueHasQuestionHasAnswersId(int qmQueueHasQuestionQmQueueId, int qmQueueHasQuestionRcasQuestionId, int rcasAnswersId, int tmTicketsId) {
       this.qmQueueHasQuestionQmQueueId = qmQueueHasQuestionQmQueueId;
       this.qmQueueHasQuestionRcasQuestionId = qmQueueHasQuestionRcasQuestionId;
       this.rcasAnswersId = rcasAnswersId;
       this.tmTicketsId = tmTicketsId;
    }
   
    public int getQmQueueHasQuestionQmQueueId() {
        return this.qmQueueHasQuestionQmQueueId;
    }
    
    public void setQmQueueHasQuestionQmQueueId(int qmQueueHasQuestionQmQueueId) {
        this.qmQueueHasQuestionQmQueueId = qmQueueHasQuestionQmQueueId;
    }
    public int getQmQueueHasQuestionRcasQuestionId() {
        return this.qmQueueHasQuestionRcasQuestionId;
    }
    
    public void setQmQueueHasQuestionRcasQuestionId(int qmQueueHasQuestionRcasQuestionId) {
        this.qmQueueHasQuestionRcasQuestionId = qmQueueHasQuestionRcasQuestionId;
    }
    public int getRcasAnswersId() {
        return this.rcasAnswersId;
    }
    
    public void setRcasAnswersId(int rcasAnswersId) {
        this.rcasAnswersId = rcasAnswersId;
    }
    public int getTmTicketsId() {
        return this.tmTicketsId;
    }
    
    public void setTmTicketsId(int tmTicketsId) {
        this.tmTicketsId = tmTicketsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmTicketHasQueueHasQuestionHasAnswersId) ) return false;
		 TmTicketHasQueueHasQuestionHasAnswersId castOther = ( TmTicketHasQueueHasQuestionHasAnswersId ) other; 
         
		 return (this.getQmQueueHasQuestionQmQueueId()==castOther.getQmQueueHasQuestionQmQueueId())
 && (this.getQmQueueHasQuestionRcasQuestionId()==castOther.getQmQueueHasQuestionRcasQuestionId())
 && (this.getRcasAnswersId()==castOther.getRcasAnswersId())
 && (this.getTmTicketsId()==castOther.getTmTicketsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQmQueueHasQuestionQmQueueId();
         result = 37 * result + this.getQmQueueHasQuestionRcasQuestionId();
         result = 37 * result + this.getRcasAnswersId();
         result = 37 * result + this.getTmTicketsId();
         return result;
   }   


}


