package com.ring.db;
// Generated Mar 24, 2022 1:49:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UmUser generated by hbm2java
 */
public class UmUser  implements java.io.Serializable {


     private Integer id;
     private PmUserRole pmUserRole;
     private String firstName;
     private String lastName;
     private Byte status;
     private Date createdAt;
     private Date updatedAt;
     private String userName;
     private String password;
     private String nicOrPassport;
     private Date dateOfBirth;
     private String mobileNumber;
     private String emailAddress;
     private Byte gender;
     private String maritialStatus;
     private String remark1;
     private String remark2;
     private int createdBy;
     private int updatedBy;
     private String passport;
     private String remark3;
     private String remark4;
     private Set pmInterfaceComponentsForCreatedBy = new HashSet(0);
     private Set qmCategoriesHasUsers = new HashSet(0);
     private Set pmInterfaceComponentsForUpdatedBy = new HashSet(0);
     private Set smSessions = new HashSet(0);
     private Set pmInterfacesForUpdatedBy = new HashSet(0);
     private Set pmInterfacesForCreatedBy = new HashSet(0);
     private Set lmLocationsHasUmUsers = new HashSet(0);
     private Set smSessionActivities = new HashSet(0);
     private Set qmQueueHasUsers = new HashSet(0);
     private Set pmInterfaceComponentHistoriesForCreatedBy = new HashSet(0);
     private Set pmInterfaceComponentHistoriesForUmUserId = new HashSet(0);
     private Set pmUserRolesForCreatedBy = new HashSet(0);
     private Set umUserHasInterfaceTopicsForCreatedBy = new HashSet(0);
     private Set pmUserRolesForUpdatedBy = new HashSet(0);
     private Set umUserHasInterfaceTopicsForUpdatedBy = new HashSet(0);
     private Set pmUserRoleHasInterfaceComponentsForUpdatedBy = new HashSet(0);
     private Set pmUserRoleHasInterfaceComponentsForCreatedBy = new HashSet(0);
     private Set umUserHasInterfaceTopicsForUmUserId = new HashSet(0);
     private Set umUserHasInterfaceComponentsForCreatedBy = new HashSet(0);
     private Set umUserHasInterfaceComponentsForUpdatedBy = new HashSet(0);
     private Set lmLocationses = new HashSet(0);
     private Set tmTicketsHasUmUsers = new HashSet(0);
     private Set pmInterfaceTopicsForCreatedBy = new HashSet(0);
     private Set umUserHasInterfaceComponentsForUmUserId = new HashSet(0);
     private Set pmInterfaceTopicsForUpdatedBy = new HashSet(0);
     private Set qmSubCategoriesHasUsers = new HashSet(0);

    public UmUser() {
    }

	
    public UmUser(int createdBy, int updatedBy) {
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
    }
    public UmUser(PmUserRole pmUserRole, String firstName, String lastName, Byte status, Date createdAt, Date updatedAt, String userName, String password, String nicOrPassport, Date dateOfBirth, String mobileNumber, String emailAddress, Byte gender, String maritialStatus, String remark1, String remark2, int createdBy, int updatedBy, String passport, String remark3, String remark4, Set pmInterfaceComponentsForCreatedBy, Set qmCategoriesHasUsers, Set pmInterfaceComponentsForUpdatedBy, Set smSessions, Set pmInterfacesForUpdatedBy, Set pmInterfacesForCreatedBy, Set lmLocationsHasUmUsers, Set smSessionActivities, Set qmQueueHasUsers, Set pmInterfaceComponentHistoriesForCreatedBy, Set pmInterfaceComponentHistoriesForUmUserId, Set pmUserRolesForCreatedBy, Set umUserHasInterfaceTopicsForCreatedBy, Set pmUserRolesForUpdatedBy, Set umUserHasInterfaceTopicsForUpdatedBy, Set pmUserRoleHasInterfaceComponentsForUpdatedBy, Set pmUserRoleHasInterfaceComponentsForCreatedBy, Set umUserHasInterfaceTopicsForUmUserId, Set umUserHasInterfaceComponentsForCreatedBy, Set umUserHasInterfaceComponentsForUpdatedBy, Set lmLocationses, Set tmTicketsHasUmUsers, Set pmInterfaceTopicsForCreatedBy, Set umUserHasInterfaceComponentsForUmUserId, Set pmInterfaceTopicsForUpdatedBy, Set qmSubCategoriesHasUsers) {
       this.pmUserRole = pmUserRole;
       this.firstName = firstName;
       this.lastName = lastName;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.userName = userName;
       this.password = password;
       this.nicOrPassport = nicOrPassport;
       this.dateOfBirth = dateOfBirth;
       this.mobileNumber = mobileNumber;
       this.emailAddress = emailAddress;
       this.gender = gender;
       this.maritialStatus = maritialStatus;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.passport = passport;
       this.remark3 = remark3;
       this.remark4 = remark4;
       this.pmInterfaceComponentsForCreatedBy = pmInterfaceComponentsForCreatedBy;
       this.qmCategoriesHasUsers = qmCategoriesHasUsers;
       this.pmInterfaceComponentsForUpdatedBy = pmInterfaceComponentsForUpdatedBy;
       this.smSessions = smSessions;
       this.pmInterfacesForUpdatedBy = pmInterfacesForUpdatedBy;
       this.pmInterfacesForCreatedBy = pmInterfacesForCreatedBy;
       this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
       this.smSessionActivities = smSessionActivities;
       this.qmQueueHasUsers = qmQueueHasUsers;
       this.pmInterfaceComponentHistoriesForCreatedBy = pmInterfaceComponentHistoriesForCreatedBy;
       this.pmInterfaceComponentHistoriesForUmUserId = pmInterfaceComponentHistoriesForUmUserId;
       this.pmUserRolesForCreatedBy = pmUserRolesForCreatedBy;
       this.umUserHasInterfaceTopicsForCreatedBy = umUserHasInterfaceTopicsForCreatedBy;
       this.pmUserRolesForUpdatedBy = pmUserRolesForUpdatedBy;
       this.umUserHasInterfaceTopicsForUpdatedBy = umUserHasInterfaceTopicsForUpdatedBy;
       this.pmUserRoleHasInterfaceComponentsForUpdatedBy = pmUserRoleHasInterfaceComponentsForUpdatedBy;
       this.pmUserRoleHasInterfaceComponentsForCreatedBy = pmUserRoleHasInterfaceComponentsForCreatedBy;
       this.umUserHasInterfaceTopicsForUmUserId = umUserHasInterfaceTopicsForUmUserId;
       this.umUserHasInterfaceComponentsForCreatedBy = umUserHasInterfaceComponentsForCreatedBy;
       this.umUserHasInterfaceComponentsForUpdatedBy = umUserHasInterfaceComponentsForUpdatedBy;
       this.lmLocationses = lmLocationses;
       this.tmTicketsHasUmUsers = tmTicketsHasUmUsers;
       this.pmInterfaceTopicsForCreatedBy = pmInterfaceTopicsForCreatedBy;
       this.umUserHasInterfaceComponentsForUmUserId = umUserHasInterfaceComponentsForUmUserId;
       this.pmInterfaceTopicsForUpdatedBy = pmInterfaceTopicsForUpdatedBy;
       this.qmSubCategoriesHasUsers = qmSubCategoriesHasUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PmUserRole getPmUserRole() {
        return this.pmUserRole;
    }
    
    public void setPmUserRole(PmUserRole pmUserRole) {
        this.pmUserRole = pmUserRole;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNicOrPassport() {
        return this.nicOrPassport;
    }
    
    public void setNicOrPassport(String nicOrPassport) {
        this.nicOrPassport = nicOrPassport;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public Byte getGender() {
        return this.gender;
    }
    
    public void setGender(Byte gender) {
        this.gender = gender;
    }
    public String getMaritialStatus() {
        return this.maritialStatus;
    }
    
    public void setMaritialStatus(String maritialStatus) {
        this.maritialStatus = maritialStatus;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public int getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(int updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getPassport() {
        return this.passport;
    }
    
    public void setPassport(String passport) {
        this.passport = passport;
    }
    public String getRemark3() {
        return this.remark3;
    }
    
    public void setRemark3(String remark3) {
        this.remark3 = remark3;
    }
    public String getRemark4() {
        return this.remark4;
    }
    
    public void setRemark4(String remark4) {
        this.remark4 = remark4;
    }
    public Set getPmInterfaceComponentsForCreatedBy() {
        return this.pmInterfaceComponentsForCreatedBy;
    }
    
    public void setPmInterfaceComponentsForCreatedBy(Set pmInterfaceComponentsForCreatedBy) {
        this.pmInterfaceComponentsForCreatedBy = pmInterfaceComponentsForCreatedBy;
    }
    public Set getQmCategoriesHasUsers() {
        return this.qmCategoriesHasUsers;
    }
    
    public void setQmCategoriesHasUsers(Set qmCategoriesHasUsers) {
        this.qmCategoriesHasUsers = qmCategoriesHasUsers;
    }
    public Set getPmInterfaceComponentsForUpdatedBy() {
        return this.pmInterfaceComponentsForUpdatedBy;
    }
    
    public void setPmInterfaceComponentsForUpdatedBy(Set pmInterfaceComponentsForUpdatedBy) {
        this.pmInterfaceComponentsForUpdatedBy = pmInterfaceComponentsForUpdatedBy;
    }
    public Set getSmSessions() {
        return this.smSessions;
    }
    
    public void setSmSessions(Set smSessions) {
        this.smSessions = smSessions;
    }
    public Set getPmInterfacesForUpdatedBy() {
        return this.pmInterfacesForUpdatedBy;
    }
    
    public void setPmInterfacesForUpdatedBy(Set pmInterfacesForUpdatedBy) {
        this.pmInterfacesForUpdatedBy = pmInterfacesForUpdatedBy;
    }
    public Set getPmInterfacesForCreatedBy() {
        return this.pmInterfacesForCreatedBy;
    }
    
    public void setPmInterfacesForCreatedBy(Set pmInterfacesForCreatedBy) {
        this.pmInterfacesForCreatedBy = pmInterfacesForCreatedBy;
    }
    public Set getLmLocationsHasUmUsers() {
        return this.lmLocationsHasUmUsers;
    }
    
    public void setLmLocationsHasUmUsers(Set lmLocationsHasUmUsers) {
        this.lmLocationsHasUmUsers = lmLocationsHasUmUsers;
    }
    public Set getSmSessionActivities() {
        return this.smSessionActivities;
    }
    
    public void setSmSessionActivities(Set smSessionActivities) {
        this.smSessionActivities = smSessionActivities;
    }
    public Set getQmQueueHasUsers() {
        return this.qmQueueHasUsers;
    }
    
    public void setQmQueueHasUsers(Set qmQueueHasUsers) {
        this.qmQueueHasUsers = qmQueueHasUsers;
    }
    public Set getPmInterfaceComponentHistoriesForCreatedBy() {
        return this.pmInterfaceComponentHistoriesForCreatedBy;
    }
    
    public void setPmInterfaceComponentHistoriesForCreatedBy(Set pmInterfaceComponentHistoriesForCreatedBy) {
        this.pmInterfaceComponentHistoriesForCreatedBy = pmInterfaceComponentHistoriesForCreatedBy;
    }
    public Set getPmInterfaceComponentHistoriesForUmUserId() {
        return this.pmInterfaceComponentHistoriesForUmUserId;
    }
    
    public void setPmInterfaceComponentHistoriesForUmUserId(Set pmInterfaceComponentHistoriesForUmUserId) {
        this.pmInterfaceComponentHistoriesForUmUserId = pmInterfaceComponentHistoriesForUmUserId;
    }
    public Set getPmUserRolesForCreatedBy() {
        return this.pmUserRolesForCreatedBy;
    }
    
    public void setPmUserRolesForCreatedBy(Set pmUserRolesForCreatedBy) {
        this.pmUserRolesForCreatedBy = pmUserRolesForCreatedBy;
    }
    public Set getUmUserHasInterfaceTopicsForCreatedBy() {
        return this.umUserHasInterfaceTopicsForCreatedBy;
    }
    
    public void setUmUserHasInterfaceTopicsForCreatedBy(Set umUserHasInterfaceTopicsForCreatedBy) {
        this.umUserHasInterfaceTopicsForCreatedBy = umUserHasInterfaceTopicsForCreatedBy;
    }
    public Set getPmUserRolesForUpdatedBy() {
        return this.pmUserRolesForUpdatedBy;
    }
    
    public void setPmUserRolesForUpdatedBy(Set pmUserRolesForUpdatedBy) {
        this.pmUserRolesForUpdatedBy = pmUserRolesForUpdatedBy;
    }
    public Set getUmUserHasInterfaceTopicsForUpdatedBy() {
        return this.umUserHasInterfaceTopicsForUpdatedBy;
    }
    
    public void setUmUserHasInterfaceTopicsForUpdatedBy(Set umUserHasInterfaceTopicsForUpdatedBy) {
        this.umUserHasInterfaceTopicsForUpdatedBy = umUserHasInterfaceTopicsForUpdatedBy;
    }
    public Set getPmUserRoleHasInterfaceComponentsForUpdatedBy() {
        return this.pmUserRoleHasInterfaceComponentsForUpdatedBy;
    }
    
    public void setPmUserRoleHasInterfaceComponentsForUpdatedBy(Set pmUserRoleHasInterfaceComponentsForUpdatedBy) {
        this.pmUserRoleHasInterfaceComponentsForUpdatedBy = pmUserRoleHasInterfaceComponentsForUpdatedBy;
    }
    public Set getPmUserRoleHasInterfaceComponentsForCreatedBy() {
        return this.pmUserRoleHasInterfaceComponentsForCreatedBy;
    }
    
    public void setPmUserRoleHasInterfaceComponentsForCreatedBy(Set pmUserRoleHasInterfaceComponentsForCreatedBy) {
        this.pmUserRoleHasInterfaceComponentsForCreatedBy = pmUserRoleHasInterfaceComponentsForCreatedBy;
    }
    public Set getUmUserHasInterfaceTopicsForUmUserId() {
        return this.umUserHasInterfaceTopicsForUmUserId;
    }
    
    public void setUmUserHasInterfaceTopicsForUmUserId(Set umUserHasInterfaceTopicsForUmUserId) {
        this.umUserHasInterfaceTopicsForUmUserId = umUserHasInterfaceTopicsForUmUserId;
    }
    public Set getUmUserHasInterfaceComponentsForCreatedBy() {
        return this.umUserHasInterfaceComponentsForCreatedBy;
    }
    
    public void setUmUserHasInterfaceComponentsForCreatedBy(Set umUserHasInterfaceComponentsForCreatedBy) {
        this.umUserHasInterfaceComponentsForCreatedBy = umUserHasInterfaceComponentsForCreatedBy;
    }
    public Set getUmUserHasInterfaceComponentsForUpdatedBy() {
        return this.umUserHasInterfaceComponentsForUpdatedBy;
    }
    
    public void setUmUserHasInterfaceComponentsForUpdatedBy(Set umUserHasInterfaceComponentsForUpdatedBy) {
        this.umUserHasInterfaceComponentsForUpdatedBy = umUserHasInterfaceComponentsForUpdatedBy;
    }
    public Set getLmLocationses() {
        return this.lmLocationses;
    }
    
    public void setLmLocationses(Set lmLocationses) {
        this.lmLocationses = lmLocationses;
    }
    public Set getTmTicketsHasUmUsers() {
        return this.tmTicketsHasUmUsers;
    }
    
    public void setTmTicketsHasUmUsers(Set tmTicketsHasUmUsers) {
        this.tmTicketsHasUmUsers = tmTicketsHasUmUsers;
    }
    public Set getPmInterfaceTopicsForCreatedBy() {
        return this.pmInterfaceTopicsForCreatedBy;
    }
    
    public void setPmInterfaceTopicsForCreatedBy(Set pmInterfaceTopicsForCreatedBy) {
        this.pmInterfaceTopicsForCreatedBy = pmInterfaceTopicsForCreatedBy;
    }
    public Set getUmUserHasInterfaceComponentsForUmUserId() {
        return this.umUserHasInterfaceComponentsForUmUserId;
    }
    
    public void setUmUserHasInterfaceComponentsForUmUserId(Set umUserHasInterfaceComponentsForUmUserId) {
        this.umUserHasInterfaceComponentsForUmUserId = umUserHasInterfaceComponentsForUmUserId;
    }
    public Set getPmInterfaceTopicsForUpdatedBy() {
        return this.pmInterfaceTopicsForUpdatedBy;
    }
    
    public void setPmInterfaceTopicsForUpdatedBy(Set pmInterfaceTopicsForUpdatedBy) {
        this.pmInterfaceTopicsForUpdatedBy = pmInterfaceTopicsForUpdatedBy;
    }
    public Set getQmSubCategoriesHasUsers() {
        return this.qmSubCategoriesHasUsers;
    }
    
    public void setQmSubCategoriesHasUsers(Set qmSubCategoriesHasUsers) {
        this.qmSubCategoriesHasUsers = qmSubCategoriesHasUsers;
    }




}


